### ISSUE TITLE
Failing to deserialize TaskState dates

### ISSUE THREAD

**Issue by cwdesautels** [hashicorp/nomad-java-sdk#10]
I've converting to using the SDK from interacting with the HTTP API directly and I've encountered deserialization problems while polling for Allocation ClientStatus changes.

Versions:
- Nomad SDK 0.7.0
- Nomad Server 0.7.1

Querying the Allocation before a task restarts works as expected, using the below code.

```
nomadAllocationsApi.info(allocationId, new QueryOptions<Allocation>().setIndex(index).setWaitStrategy(WaitStrategy.waitForSeconds(60))).getValue()
```

However, I'm seeing failures if my Tasks ever restart. It seems the TaskState LastRestart field is being populated with an unparsable date, see relevant stacktrace:

```
Caused by: com.hashicorp.nomad.javasdk.ResponseParsingException: Unable to parse [simple type, class com.hashicorp.nomad.apimodel.Allocation] from response body JSON: **{Omitted}**
        at com.hashicorp.nomad.javasdk.JsonParser.extractValue(JsonParser.java:26)
        at com.hashicorp.nomad.javasdk.ResponseAdapter.apply(ResponseAdapter.java:30)
        at com.hashicorp.nomad.javasdk.NomadApiClient.execute(NomadApiClient.java:335)
        at com.hashicorp.nomad.javasdk.ApiBase.executeServerQueryRaw(ApiBase.java:221)
        at com.hashicorp.nomad.javasdk.ApiBase.executeServerQuery(ApiBase.java:116)
        at com.hashicorp.nomad.javasdk.ApiBase.executeServerQuery(ApiBase.java:101)
        at com.hashicorp.nomad.javasdk.AllocationsApi.info(AllocationsApi.java:46)
        at myclass.NomadClient.waitForAllocationTerminalState(NomadClient.java:151)
        at myclass.NomadClient$waitForAllocationTerminalState$1.call(Unknown Source)
        at build_20x9ms6t7qn7fr73ampgndhe8$_run_closure10$_closure20.doCall(/Users/me/ws/nomad-client/build.gradle:201)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:726)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:699)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        ... 36 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.util.Date from String "2018-03-29T06:03:44.970250143-07:00": not a valid representation (error: Failed to parse Date value '2018-03-29T06:03:44.970250143-07:00': Can not parse date "2018-03-29T06:03:44.970250143-0700": while it seems to fit format 'yyyy-MM-dd'T'HH:mm:ss.SSSZ', parsing fails (leniency? null))
```

Snippet of JSON message:

```
{
  "TaskStates":{
    "a":{
       "LastRestart":"2018-03-29T06:03:44.970250143-07:00",
       "StartedAt":"0001-01-01T00:00:00Z",
       "FinishedAt":"0001-01-01T00:00:00Z",
    }
  }
}
```

Any insight or a fix would be appreciated.

**Comment by cwdesautels** [comment]
I worked around this issue by providing my own TaskState implementation and removing all Date fields.

**Comment by cgbaker** [comment]
@cwdesautels , what platform were you on? I ran into this just recently on darwin... the problem was the date serialization performed by nomad was dependent on the local timezone of the node running the agent. The workaround that I am using is to run the agent with the environment variable `TZ=UTC`, e.g.,: 
```
TZ=UTC nomad agent ... 
```

**Comment by cgbaker** [comment]
closing this in favor of https://github.com/hashicorp/nomad-java-sdk/issues/6

**Comment by cwdesautels** [comment]
@cgbaker Thanks for the reply, your fix is preferred compared to replacing classes :)

If I can recall my environments were OSX High Sierra, Alpine 3.x and CentOS 5.x
